all: Basic.class Functional.class Collection.class

Basic.class: Basic.scala
	fsc Basic.scala

Functional.class: Functional.scala
	fsc Functional.scala

Collection.class: Collection.scala
	fsc Collection.scala

clean:
	rm -rf *.class
